### ISSUE TITLE
Object not iterable

### ISSUE THREAD

**Issue by paulevolve** [automainint/sea-offers-bot-js#11]
TypeError: _0x31bcbc[_0x31a4b6] is not iterable

Hello, I am getting this error from nowhere. I have some bots running 24/7, everything was working fine since today when I get this error on all servers. I did not made any modifications on the config file or anything, the error just appeared out of nowhere.
Any thoughts? 

Thank you.

**Comment by paulevolve** [comment]
Init config...
Init OpenSea SDK...
Using network: mainnet...
Using Alchemy...
Using provided OpenSea API key...
Init event handlers...

Starting...
Auto price enabled.
Delay per line: 0 ms.


   1 Acquiring asset...
     Address: 0x3bf2922f4520a8ba0c2efc3d2a1539678dad5e9d
     Id:      6037

   Fetching
   https://api.opensea.io/api/v1/asset/0x3bf2922f4520a8ba0c2efc3d2a1539678dad5e9d/6037/?

   1 Internal processing error.

TypeError: _0x31bcbc[_0x31a4b6] is not iterable
    at _0x7dfccc (D:\Workspace\Python\PycharmProjects\Evolve999\offers.js:732:46)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async _0x57e0b3 (D:\Workspace\Python\PycharmProjects\Evolve999\offers.js:768:40)
    at async _0x51a19b (D:\Workspace\Python\PycharmProjects\Evolve999\offers.js:777:13)
    at async _0x27d979 (D:\Workspace\Python\PycharmProjects\Evolve999\offers.js:806:273)
    at async _0x3462c3 (D:\Workspace\Python\PycharmProjects\Evolve999\offers.js:825:43)

 ! 1 Offer discarded. Too many errors.
     Address: 0x3bf2922f4520a8ba0c2efc3d2a1539678dad5e9d
     Id:      6037

Done.

**Comment by paulevolve** [comment]
I've tried this on multiple devices with different config file and different wallets. Same results.

**Comment by paulevolve** [comment]
It may be an opensea update.

**Comment by Kruss2465** [comment]
Same thing for me. Tried on multiple devices and wallets. Not working

**Comment by automainint** [comment]
Fixed in v0.2.16
