### ISSUE TITLE
triggerUncaughtException

### ISSUE THREAD

**Issue by mrtornado** [automainint/sea-offers-bot-js#2]
getting this error and have no clue how to fix it , I used the nvm use 8 and nvm use 16 trick to get past the first error but now getting this, I get it on the test network.

```
node offers.js --config=config.json --file=list.txt --verbose

Init config...

Init config...
Init OpenSea SDK...
Using network: rinkeby...
Using Infura...
Init event handlers...

Starting...
Instance ID: 7484-169
Auto price enabled.
Default floor: 0.001, roof: 100, epsilon: 0.001.
Delay per line: 1000--2000 ms.


   1 Acquiring asset...
     Address: 0x08a62684d8d609dcc7cfb0664cf9aabec86504e5
     Id:      100

   1 Processing...
     Address: 0x08a62684d8d609dcc7cfb0664cf9aabec86504e5
     Id:      100
     Price:   0.007

 % Order created
{
  code: -32603,
  message: 'Unknown Error: internal service failure\n',
  data: { originalError: {} },
  stack: 'Error: Unknown Error: internal service failure\n' +
    '\n' +
    '    at Request._callback (/Users/toro/opensea/sea-offers-bot-js/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js:57:23)\n' +
    '    at Request.self.callback (/Users/toro/opensea/sea-offers-bot-js/node_modules/request/request.js:185:22)\n' +
    '    at Request.emit (node:events:390:28)\n' +
    '    at Request.<anonymous> (/Users/toro/opensea/sea-offers-bot-js/node_modules/request/request.js:1154:10)\n' +
    '    at Request.emit (node:events:390:28)\n' +
    '    at IncomingMessage.<anonymous> (/Users/toro/opensea/sea-offers-bot-js/node_modules/request/request.js:1076:12)\n' +
    '    at Object.onceWrapper (node:events:509:28)\n' +
    '    at IncomingMessage.emit (node:events:402:35)\n' +
    '    at endReadableNT (node:internal/streams/readable:1343:12)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:83:21)'
}

 * 1 Offer succeed with errors.
     Address: 0x08a62684d8d609dcc7cfb0664cf9aabec86504e5
     Id:      100
     Price:   0.007

   1 Internal error due processing.
```

**Comment by mrtornado** [comment]
On mainnet it seems to be working but I get it blocked by cloudflare, btw I'm not using an opensea api key, could that be the problem ? 
I have tried with proxy and without proxy, same result

```
node offers.js --config=config.json --file=list.txt --proxy=proxy.txt --verbose

Init config...

Init config...
Init OpenSea SDK...
Using network: mainnet...
Using Infura...
Init proxies...

   Switch proxy 1 - http://168.91.98.153:44555

Init event handlers...

Starting...
Instance ID: 6928-463
Auto price enabled.
Default floor: 0.001, roof: 100, epsilon: 0.001.
Delay per line: 1000--2000 ms.


   1 Acquiring asset...
     Address: 0x1eff5ed809c994ee2f500f076cef22ef3fd9c25d
     Id:      8

   1 Processing...
     Address: 0x1eff5ed809c994ee2f500f076cef22ef3fd9c25d
     Id:      8
     Price:   0.008

 % Order created

 * 1 Offer succeed with errors.
     Address: 0x1eff5ed809c994ee2f500f076cef22ef3fd9c25d
     Id:      8
     Price:   0.008

   1 Request was blocked by Cloudflare.

Done.
```

**Comment by automainint** [comment]
Can you set in config `"log_full": true`
And then show your log?

**Comment by automainint** [comment]
On mainnet, your proxy probably blacklisted by Cloudflare. Can you make it work without proxy?

**Comment by automainint** [comment]
To pass Cloudflare, add in config `user_agent` and `cookie`. You can pass captcha manually in browser and then use cookie `cf_clearance=...`

**Comment by automainint** [comment]
If your proxy blacklisted by Cloudflare, you will probably need different proxy, ideally setup your own private proxy.
